### ISSUE TITLE
Question: statsrelay support UDP?

### ISSUE THREAD

**Issue by keyboardfann** [uber/statsrelay#70]
Hello All,
    Does statsrelay support UDP protocol? Here is my flow , metrics -> LVS -> statsrelay -> telegraf statsd udp input plugin.

statsrelay.conf
```
statsd:
  bind: 10.62.4.158:12001
  tcp_cork: false
  validate: true
  shard_map:
    0: 10.62.4.158:12100
```

telegraf statsd plugin listen on UDP 12100
```
ss -tunlp |grep 12100
udp    UNCONN     0      0      10.62.4.158:12100                 *:* 
```

run statsrelay
```
[root@tng1396 ~]# /usr/local/bin/statsrelay -c statsrelay.conf 
ERROR: tcpclient[10.62.4.158/12100/tcp]: Connect failed: Connection refused
```

**Comment by JeremyGrosser** [comment]
No, statsrelay only supports TCP for connecting to backends.

**Comment by JeremyGrosser** [comment]
Oh, I might be wrong about that... Just reading the code, I think if you do "0:10.62.4.158:12100:udp" in the shard map, it'll work.

**Comment by keyboardfann** [comment]
Dear @JeremyGrosser ,
    Thank you for answer the question. I add udp to config and start statsrelay , statsrelay show  Unexpectedly received zero-length UDP payload.

statsrelay.conf
```
statsd:
  bind: 10.62.4.158:12001
  tcp_cork: false
  validate: true
  shard_map:
    0: 10.62.4.158:12100:udp
```

start statsrelay
```
/usr/local/bin/statsrelay -c statsrelay.conf 
ERROR: stats: Unexpectedly received zero-length UDP payload.
ERROR: stats: Unexpectedly received zero-length UDP payload.
ERROR: stats: Unexpectedly received zero-length UDP payload.
ERROR: stats: Unexpectedly received zero-length UDP payload.
ERROR: stats: Unexpectedly received zero-length UDP payload.
ERROR: stats: Unexpectedly received zero-length UDP payload.

```
